# Generated by Django 2.0.2 on 2018-04-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Payment_method',
            fields=[
                ('customer_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_card_number', models.CharField(max_length=16)),
                ('payment_method_details', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=6)),
                ('email_address', models.EmailField(max_length=20)),
                ('login_name', models.CharField(max_length=15)),
                ('login_password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('add_line1', models.CharField(max_length=30)),
                ('add_line2', models.CharField(max_length=30)),
                ('add_line3', models.CharField(max_length=15)),
                ('pin_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Invoice_Status_Codes',
            fields=[
                ('invoice_status_code', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_status_description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Order_Status_Codes',
            fields=[
                ('order_status_code', models.AutoField(primary_key=True, serialize=False)),
                ('order_status_description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Payment_Method',
            fields=[
                ('payment_method_code', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Product_Types',
            fields=[
                ('product_type_code', models.AutoField(primary_key=True, serialize=False)),
                ('product_type_description', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='customer_payment_method',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Customers'),
        ),
        migrations.AddField(
            model_name='customer_payment_method',
            name='payment_method_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Ref_Payment_Method'),
        ),
    ]
