# Generated by Django 2.0.2 on 2018-04-07 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_order_placed', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('order_details', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Customers')),
                ('order_status_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Ref_Order_Status_Codes')),
            ],
        ),
    ]
