# Generated by Django 2.0.2 on 2018-04-07 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('payment_amount', models.FloatField(max_length=15)),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Invoices')),
            ],
        ),
    ]
