# Generated by Django 2.0.2 on 2018-04-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_shipments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_merchandise_authorization', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.FloatField(max_length=20)),
                ('product_color', models.CharField(max_length=15)),
                ('product_size', models.CharField(max_length=10)),
                ('product_description', models.CharField(max_length=20)),
                ('other_product_details', models.CharField(max_length=20)),
                ('product_type_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Ref_Product_Types')),
            ],
        ),
    ]
