# Generated by Django 2.0.2 on 2018-04-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Order_Item_Status_Codes',
            fields=[
                ('order_item_status_code', models.AutoField(primary_key=True, serialize=False)),
                ('order_item_status_description', models.CharField(max_length=10)),
            ],
        ),
    ]
