# Generated by Django 2.0.2 on 2018-04-07 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_ref_order_item_status_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_item_quantity', models.IntegerField()),
                ('order_item_price', models.FloatField(max_length=20)),
                ('RMA_number', models.CharField(max_length=15)),
                ('RMA_issued_by', models.CharField(max_length=20)),
                ('RMA_issued_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('other_order_item_details', models.CharField(max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Orders')),
                ('order_item_status_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Ref_Order_Item_Status_Codes')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Products')),
            ],
        ),
    ]
