# Generated by Django 2.0.2 on 2018-04-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment_Items',
            fields=[
                ('shipment_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Order_Items')),
                ('shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Shipments')),
            ],
        ),
    ]
