# Generated by Django 2.0.2 on 2018-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_shipment_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img1',
            field=models.ImageField(default='', upload_to='product_img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_img2',
            field=models.ImageField(default='', upload_to='product_img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_img3',
            field=models.ImageField(default='', upload_to='product_img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_img4',
            field=models.ImageField(default='', upload_to='product_img/'),
            preserve_default=False,
        ),
    ]
