# Generated by Django 2.0.2 on 2018-04-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180408_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='other_product_details',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.CharField(max_length=50),
        ),
    ]
