# Generated by Django 2.0.2 on 2018-04-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20180410_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='add_line1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customers',
            name='add_line2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customers',
            name='add_line3',
            field=models.CharField(max_length=100),
        ),
    ]
