# Generated by Django 2.0.2 on 2018-04-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20180410_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='login_name',
            field=models.CharField(max_length=50, primary_key=True),
        ),
    ]
