# Generated by Django 1.11.12 on 2019-08-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_remove_invoices_invoice_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_details',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
